# Dependencies
highlighter:      rouge
layout: default
comments: true
# other options
gems:
  - jekyll-paginate
  - jekyll-feed

# Permalinks
permalink:              /blog/:categories/:title/
# permalink:            blog/:categories/:year/:month/:day/:title/

# SetupeTdataEdge
title:            'Mulugeta Alemayehu Dagnaw'
name:             'Mulugeta Alemayehu Dagnaw'
#tagline:          ''
description:      'mathematician'
url:              'https://muledagnaw.github.io'
baseurl:          'https://muledagnaw.github.io'
# blogurl:          /blog/

# Assets
images:         '/img'
pdfs:           '/pdf'

author:
  name:           'Mulugeta Alemayehu Dagnaw'
  url:            'muledagnaw.github.io'
  email:          'malemayehu3@gmail.com'
  github:         'https://github.com/muledagnaw'
  github_io_url:  "http://muledagnaw.github.io"
  facebook:       'https://https://www.facebook.com/mulugeta.alemayehu.94'
  twitter:        'https://twitter.com/malemayehu3'
  linkedin:       'https://www.linkedin.com/in/mulugeta-alemayehu-dagnaw/'
  slack:          'https://et-carpentries.slack.com'
  disqus_shortname: Mulugeta
 

paginate:         3
# paginate_path:    "/blog/page:num/"

# Custom vars
version:          2.1.0

github:           
  repo:           https://github.com/muledagnaw/muledagnaw.github.io

# Collections
collections:
  - projects
  - talks

feed:
  path: atom.xml
# defaults:
#   -
#     scope:
#       path: ""
#       type: "projects" # a collection in your site, in plural form
#     values:
#       layout: "default"
# Default Settings
